### ISSUE TITLE
ABL Temporal Bone Segmentation extension

### ISSUE THREAD

**Issue by ben-connors** [Slicer/ExtensionsIndex#1732]
I was wondering if there has been any progress regarding the build error with the ABL Temporal Bone Segmentation extension; I implemented the suggested workaround in the extension's repository but the extension is not currently being built (due to 38dd4b1046f71f370532eb037404e9b7bd97cc39).

**Comment by lassoan** [comment]
Thanks for the reminder, I'll re-enable the extension build tonight.

**Comment by jamesobutler** [comment]
@lassoan Should this issue be closed now that ABLTemporalBoneSegmentation has been archived as of https://github.com/Slicer/ExtensionsIndex/commit/4c81c24f2d0576d721ac805207658bcade73ecf4?

**Comment by lassoan** [comment]
Yes, closing this issue now. @ben-connors the extension is not built for Slicer preview releases and upcoming stable releases. If you would like have the extension in the extension manager and can test (and if needed fix) the build locally then let us know and we will work together on re-enabling the build.

**Comment by jamesobutler** [comment]
@lassoan The following extensions from the Auditory-Biophysics-Lab can be reconsidered for re-enabling since the following PRs were merged.
[Slicer-ABLTemporalBoneSegmentation](https://github.com/Auditory-Biophysics-Lab/Slicer-ABLTemporalBoneSegmentation) - https://github.com/Auditory-Biophysics-Lab/Slicer-ABLTemporalBoneSegmentation/pull/6
[Slicer-BoneThicknessMapping](https://github.com/Auditory-Biophysics-Lab/Slicer-BoneThicknessMapping) - https://github.com/Auditory-Biophysics-Lab/Slicer-BoneThicknessMapping/pull/5
