### ISSUE TITLE
Bad dependencies kill entire extension build

### ISSUE THREAD

**Issue by sjh26** [Slicer/ExtensionsIndex#1758]
[SlicerVideoCamera name change](https://github.com/Slicer/ExtensionsIndex/commit/93d1942ed51a5c576f477dab77df9529ce788754) introduced this [bug](https://github.com/Slicer/ExtensionsIndex/commit/4181b49933cca4bf1420d1b8f7b54017bbfe131c) where an extension had a non-existent dependency.

Resulting [CMake Error](https://slicer.cdash.org/build/2225046/configure) terminated the whole build process.

**Comment by lassoan** [comment]
Although severity of this issue is moderate/high (breaks one nightly build), but probability of happening is quite low (happens about once a year) and its detectability is also very high, the overall risk of leaving this issue unresolved could be acceptable. But of course if we can figure out a nice solution then it is even better.

Maybe the most useful would be to have a github action that would test each commit (read all the extension names and dependencies from the s4ext files and check if a tree can be build from it).

**Comment by lassoan** [comment]
It turned out we already have an extension description check that was very easy to extend to check for valid dependencies. See the references pull request. Please have a look at the PR #1759.

**Comment by lassoan** [comment]
I've sent a test pull request and it has failed, correctly, as expected:

https://app.circleci.com/pipelines/github/Slicer/ExtensionsIndex/560/workflows/19e9762b-8d54-4429-b8bd-910c926ebba8/jobs/1608

![image](https://user-images.githubusercontent.com/307929/116143854-a736c380-a6a9-11eb-8334-0338bfe60e89.png)
